import {
  Evidence,
  JobRole,
  PortfolioSettings,
  Skill,
  TelemetryMetrics,
  User,
} from '../types/passport';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-student-1',
    name: 'Alex Rivera',
    email: 'alex.rivera@university.edu',
    role: 'student',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Computer Science & Engineering',
    graduationYear: 2025,
    bio: 'Passionate full-stack developer focusing on scalable distributed systems and cloud architecture.',
    institution: 'Tech Institute of Science',
    title: 'Senior Computer Science Undergraduate',
  },
  {
    id: 'usr-student-2',
    name: 'Sophia Chen',
    email: 'sophia.c@university.edu',
    role: 'student',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    department: 'Software Engineering',
    graduationYear: 2025,
    bio: 'Machine learning researcher and data engineering specialist.',
    institution: 'Tech Institute of Science',
    title: 'Data Science Undergraduate',
  },
  {
    id: 'usr-verifier-1',
    name: 'Dr. Sarah Jenkins',
    email: 's.jenkins@university.edu',
    role: 'verifier',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Computer Science & Engineering',
    institution: 'Tech Institute of Science',
    title: 'Associate Professor & Lab Lead',
  },
  {
    id: 'usr-verifier-2',
    name: 'Prof. David Miller',
    email: 'd.miller@university.edu',
    role: 'verifier',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    department: 'Software Systems',
    institution: 'Tech Institute of Science',
    title: 'Department Chair & Systems Verifier',
  },
  {
    id: 'usr-recruiter-1',
    name: 'Elena Rostova',
    email: 'elena@techcorp-talent.com',
    role: 'recruiter',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    department: 'Talent Acquisition',
    institution: 'Global Tech Solutions',
    title: 'Senior University Talent Partner',
  },
  {
    id: 'usr-admin-1',
    name: 'Lead Systems Admin',
    email: 'admin@passport.edu',
    role: 'admin',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    department: 'Governance Office',
    institution: 'Passport Governance Office',
    title: 'Lead Systems Architect & Notary Admin',
  },
];

export const INITIAL_SKILLS: Skill[] = [
  {
    id: 'skill-react-18',
    name: 'React 18 & Frontend Architecture',
    category: 'Frontend Engineering',
    taxonomyVersion: 1,
    description: 'Concurrent rendering, custom hooks, virtualized lists, state management, and performance benchmarking.',
    icon: 'code',
    rubricCriteria: [
      { id: 'c-rc-1', name: 'Concurrent Rendering & Hooks', maxPoints: 30, description: 'Correct usage of useTransition, useDeferredValue, and custom hooks.' },
      { id: 'c-rc-2', name: 'Component Architecture & State', maxPoints: 30, description: 'Clean modular component design, Context API/Redux setup.' },
      { id: 'c-rc-3', name: 'Performance & Virtualization', maxPoints: 20, description: 'Sub-50ms list virtualized rendering performance.' },
      { id: 'c-rc-4', name: 'Testing & Documentation', maxPoints: 20, description: 'Vitest unit tests and clear inline technical documentation.' },
    ],
  },
  {
    id: 'skill-typescript-5',
    name: 'TypeScript 5 Advanced Type Systems',
    category: 'Software Architecture',
    taxonomyVersion: 1,
    description: 'Generics, conditional types, mapped types, strict null checks, and AST compiler configurations.',
    icon: 'terminal',
    rubricCriteria: [
      { id: 'c-ts-1', name: 'Generics & Utility Types', maxPoints: 35, description: 'Demonstrates advanced generic constraints and infer keywords.' },
      { id: 'c-ts-2', name: 'Strict Type Safety', maxPoints: 35, description: 'Zero usage of `any` types with 100% strict compiler flags.' },
      { id: 'c-ts-3', name: 'API Contract Typing', maxPoints: 30, description: 'End-to-end typed REST and GraphQL schema definitions.' },
    ],
  },
  {
    id: 'skill-docker-k8s',
    name: 'Docker & Kubernetes Cloud DevOps',
    category: 'Cloud & Infrastructure',
    taxonomyVersion: 1,
    description: 'Containerization, multi-stage Dockerfiles, Helm charts, ingress controllers, and auto-scaling pods.',
    icon: 'cloud',
    rubricCriteria: [
      { id: 'c-dk-1', name: 'Dockerfile Optimization', maxPoints: 30, description: 'Multi-stage builds producing minimal Alpine image footprints.' },
      { id: 'c-dk-2', name: 'Kubernetes Pod Manifests', maxPoints: 40, description: 'Deployment specs with resource limits, liveness & readiness probes.' },
      { id: 'c-dk-3', name: 'CI/CD & Ingress Routing', maxPoints: 30, description: 'Automated GitHub Actions workflow and NGINX Ingress config.' },
    ],
  },
  {
    id: 'skill-ml-python',
    name: 'Python ML & Deep Learning',
    category: 'Data Science & AI',
    taxonomyVersion: 1,
    description: 'PyTorch neural networks, scikit-learn models, data preprocessing, and model deployment APIs.',
    icon: 'auto_awesome',
    rubricCriteria: [
      { id: 'c-ml-1', name: 'Model Architecture & Training', maxPoints: 40, description: 'Proper PyTorch/TensorFlow network definition and hyperparameter tuning.' },
      { id: 'c-ml-2', name: 'Feature Engineering & Data Pipeline', maxPoints: 30, description: 'Clean data normalization, handling missing values, train/val split.' },
      { id: 'c-ml-3', name: 'Model Validation & Evaluation', maxPoints: 30, description: 'ROC-AUC, F1-score analysis, confusion matrix visualization.' },
    ],
  },
  {
    id: 'cybersecurity-defense',
    name: 'Cybersecurity & Ethical Hacking',
    category: 'Cybersecurity & Governance',
    taxonomyVersion: 1,
    description: 'Network security auditing, SIEM log analysis, penetration testing, zero-trust architecture, and vulnerability remediation.',
    icon: 'shield',
    rubricCriteria: [
      { id: 'c-cs-1', name: 'Vulnerability Assessment & OWASP', maxPoints: 35, description: 'Identification and patch remediation of OWASP Top 10 web vulnerabilities.' },
      { id: 'c-cs-2', name: 'Zero-Trust Architecture', maxPoints: 35, description: 'Least-privilege IAM policy design and encrypted communication channels.' },
      { id: 'c-cs-3', name: 'SIEM Threat Detection', maxPoints: 30, description: 'Automated Snort/Elastic log alert rules for security incident detection.' },
    ],
  },
  {
    id: 'ai-ml-engineering',
    name: 'Generative AI & LLM Engineering',
    category: 'Data Science & AI',
    taxonomyVersion: 1,
    description: 'RAG vector search pipelines, OpenAI/LangChain orchestration, Llama 3 fine-tuning, and model quantization.',
    icon: 'psychology',
    rubricCriteria: [
      { id: 'c-llm-1', name: 'RAG Vector Search Architecture', maxPoints: 40, description: 'Sub-200ms semantic retrieval using PGVector and hybrid search.' },
      { id: 'c-llm-2', name: 'LLM Fine-Tuning & Quantization', maxPoints: 30, description: 'QLoRA fine-tuning and GGUF quantization for local edge inference.' },
      { id: 'c-llm-3', name: 'Prompt Safety & Evaluation', maxPoints: 30, description: 'Guardrail validation, hallucination detection, and benchmark scoring.' },
    ],
  },
  {
    id: 'product-management',
    name: 'Product Management & Agile Operations',
    category: 'Management & Operations',
    taxonomyVersion: 1,
    description: 'Product Requirement Documents (PRDs), user story mapping, sprint velocity tracking, and OKR alignment.',
    icon: 'inventory_2',
    rubricCriteria: [
      { id: 'c-pm-1', name: 'PRD & Feature Specification', maxPoints: 35, description: 'Detailed user persona research, acceptance criteria, and technical specs.' },
      { id: 'c-pm-2', name: 'Agile Sprint Execution', maxPoints: 35, description: 'Jira backlog grooming, burndown tracking, and sprint retrospectives.' },
      { id: 'c-pm-3', name: 'Data-Driven OKR Tracking', maxPoints: 30, description: 'Definition of ARR, churn, and retention KPIs with analytics telemetry.' },
    ],
  },
  {
    id: 'database-engineering',
    name: 'Database Architecture & Distributed SQL',
    category: 'Backend & Data',
    taxonomyVersion: 1,
    description: 'Relational schema design (3NF), B-tree/GIN index optimization, Redis caching, and ACID transaction safety.',
    icon: 'database',
    rubricCriteria: [
      { id: 'c-db-1', name: 'Schema Design & Normalization', maxPoints: 40, description: '3NF relational schemas, foreign key constraints, and migration scripts.' },
      { id: 'c-db-2', name: 'Query Plan Optimization', maxPoints: 30, description: 'EXPLAIN ANALYZE execution plan tuning and composite indexing.' },
      { id: 'c-db-3', name: 'Caching & Replication', maxPoints: 30, description: 'Redis sub-10ms cache invalidation and multi-AZ streaming replication.' },
    ],
  },
  {
    id: 'mobile-development',
    name: 'Cross-Platform Mobile Engineering',
    category: 'Mobile Engineering',
    taxonomyVersion: 1,
    description: 'Flutter & React Native mobile applications, BLoC/Redux state management, offline SQLite sync, and Fastlane CI/CD.',
    icon: 'smartphone',
    rubricCriteria: [
      { id: 'c-mb-1', name: 'Mobile UI & State Management', maxPoints: 35, description: 'Responsive mobile design with BLoC or React Native state providers.' },
      { id: 'c-mb-2', name: 'Offline Data Synchronization', maxPoints: 35, description: 'SQLite local caching with background conflict-free sync.' },
      { id: 'c-mb-3', name: 'Device APIs & Release CI/CD', maxPoints: 30, description: 'Camera/GPS hardware integration and Fastlane TestFlight deployment.' },
    ],
  },
];

export const INITIAL_EVIDENCES: Evidence[] = [
  {
    id: 'evid-101',
    userId: 'usr-student-1',
    studentName: 'Alex Rivera',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    studentEmail: 'alex.rivera@university.edu',
    department: 'Computer Science & Engineering',
    skillId: 'skill-react-18',
    skillName: 'React 18 & Frontend Architecture',
    skillCategory: 'Frontend Engineering',
    type: 'REPOSITORY',
    title: 'High-Throughput React 18 Telemetry Dashboard Engine',
    description: 'Built a distributed telemetry dashboard using React 18, TypeScript, and Vite. Implemented custom virtualized list rendering handling 100,000 data points sub-50ms with 98% unit test coverage in Vitest.',
    fileRef: 'github.com/alexrivera/virtualized-dashboard',
    externalUrl: 'https://github.com/alexrivera/virtualized-dashboard',
    status: 'APPROVED',
    submittedAt: '2026-08-01T10:30:00Z',
    updatedAt: '2026-08-02T14:15:00Z',
    contentHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    aiScore: {
      confidenceScore: 0.94,
      suggestedLevel: 'Expert',
      similarityFlag: false,
      rubricSuggestions: { 'c-rc-1': 30, 'c-rc-2': 29, 'c-rc-3': 20, 'c-rc-4': 19 },
      summary: 'High technical alignment with React 18 concurrent rendering specs. Code repository demonstrates clean hooks abstraction and performance benchmarks.',
    },
    verification: {
      id: 'ver-301',
      evidenceId: 'evid-101',
      verifierId: 'usr-verifier-1',
      verifierName: 'Dr. Sarah Jenkins',
      verifierAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      decision: 'APPROVE',
      proficiencyLevel: 'Expert',
      rubricScores: { 'c-rc-1': 30, 'c-rc-2': 30, 'c-rc-3': 20, 'c-rc-4': 18 },
      totalScore: 98,
      comments: 'Exceptional work. Code structure adheres to enterprise React 18 patterns. Virtualized rendering performance verified on 100k data points.',
      decidedAt: '2026-08-02T14:15:00Z',
    },
  },
  {
    id: 'evid-102',
    userId: 'usr-student-1',
    studentName: 'Alex Rivera',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    studentEmail: 'alex.rivera@university.edu',
    department: 'Computer Science & Engineering',
    skillId: 'skill-docker-k8s',
    skillName: 'Docker & Kubernetes Cloud DevOps',
    skillCategory: 'Cloud & Infrastructure',
    type: 'CERTIFICATE',
    title: 'Google Cloud Platform (GCP) & Docker Certified Cloud Architect',
    description: 'Multi-stage Docker containerization pipeline with Helm chart deployment on Google Cloud Platform (GCP) Kubernetes Engine (GKE).',
    fileRef: 'gcp_docker_k8s_certificate.pdf',
    externalUrl: 'https://www.credly.com/org/google',
    status: 'APPROVED',
    submittedAt: '2026-08-03T11:00:00Z',
    updatedAt: '2026-08-04T09:30:00Z',
    contentHash: '7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
    issuerInfo: {
      issuerId: 'google',
      issuerName: 'Google Cloud Platform',
      category: 'MNC',
      logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/google/google-original.svg',
      brandColor: 'bg-blue-50 text-blue-900 border-blue-300',
      credentialId: 'GOOG-GCP-8849-2025',
      signatureStatus: 'RSA-256 Public Key Verified by Google Cloud',
      verificationEndpoint: 'https://www.credly.com/org/google',
    },
    aiScore: {
      confidenceScore: 0.88,
      suggestedLevel: 'Advanced',
      similarityFlag: false,
      rubricSuggestions: { 'c-dk-1': 28, 'c-dk-2': 36, 'c-dk-3': 26 },
      summary: 'Verified Google Cloud Platform certificate with valid RSA-256 signature and multi-stage Docker deployment manifests.',
    },
    verification: {
      id: 'ver-302',
      evidenceId: 'evid-102',
      verifierId: 'usr-verifier-2',
      verifierName: 'Prof. David Miller',
      verifierAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
      decision: 'APPROVE',
      proficiencyLevel: 'Advanced',
      rubricScores: { 'c-dk-1': 28, 'c-dk-2': 38, 'c-dk-3': 28 },
      totalScore: 94,
      comments: 'Google Cloud Platform certificate verified with authentic RSA signature. Kubernetes manifest specs satisfy production limits.',
      decidedAt: '2026-08-04T09:30:00Z',
    },
  },
  {
    id: 'evid-103',
    userId: 'usr-student-2',
    studentName: 'Sophia Chen',
    studentAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    studentEmail: 'sophia.c@university.edu',
    department: 'Software Engineering',
    skillId: 'skill-ml-python',
    skillName: 'Python ML & Deep Learning',
    skillCategory: 'Data Science & AI',
    type: 'CERTIFICATE',
    title: 'IIT Bombay & NPTEL Advanced Machine Learning & PyTorch Specialization',
    description: 'PyTorch convolutional neural network for automated medical image anomaly detection with 94.2% ROC-AUC score.',
    fileRef: 'iit_bombay_ml_certificate.pdf',
    externalUrl: 'https://nptel.ac.in/noc/verify',
    status: 'APPROVED',
    submittedAt: '2026-08-05T14:20:00Z',
    updatedAt: '2026-08-06T16:00:00Z',
    contentHash: 'c4ca4238a0b923820dcc509a6f75849b00000000000000000000000000000000',
    issuerInfo: {
      issuerId: 'iit_bombay',
      issuerName: 'IIT Bombay (Indian Institute of Technology)',
      category: 'INDIAN_UNIVERSITY',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1d/IIT_Bombay_Logo.svg',
      brandColor: 'bg-emerald-50 text-emerald-900 border-emerald-300',
      credentialId: 'IITB-NPTEL-ML-9921-2025',
      signatureStatus: 'Digital Signature Authenticated by IIT Bombay Governance',
      verificationEndpoint: 'https://www.iitb.ac.in/verify',
    },
    aiScore: {
      confidenceScore: 0.91,
      suggestedLevel: 'Advanced',
      similarityFlag: false,
      rubricSuggestions: { 'c-ml-1': 36, 'c-ml-2': 28, 'c-ml-3': 28 },
      summary: 'Authentic IIT Bombay certification with PyTorch model notebooks demonstrating 94.2% ROC-AUC scores.',
    },
    verification: {
      id: 'ver-303',
      evidenceId: 'evid-103',
      verifierId: 'usr-verifier-1',
      verifierName: 'Dr. Sarah Jenkins',
      verifierAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      decision: 'APPROVE',
      proficiencyLevel: 'Advanced',
      rubricScores: { 'c-ml-1': 38, 'c-ml-2': 28, 'c-ml-3': 29 },
      totalScore: 95,
      comments: 'IIT Bombay credential verified. Impressive PyTorch neural network training metrics and cross-validation logs.',
      decidedAt: '2026-08-06T16:00:00Z',
    },
  },
];

export const INITIAL_PORTFOLIO_SETTINGS: PortfolioSettings = {
  id: 'ps-alex-rivera',
  userId: 'usr-student-1',
  shareableSlug: 'alex-rivera-passport',
  isPublic: true,
  visibleFields: {
    showEmail: true,
    showDepartment: true,
    showGraduationYear: true,
    showTimeline: true,
  },
};

export const INITIAL_TELEMETRY: TelemetryMetrics = {
  totalSubmissions: 3,
  pendingQueueDepth: 0,
  approvedCount: 3,
  rejectedCount: 0,
  needsInfoCount: 0,
  avgTurnaroundHours: 18.5,
  aiScoringLatencyMs: 142,
  aiVerifierAgreementRate: 92,
  auditLedgerStatus: 'HEALTHY',
};

export const INITIAL_JOB_ROLES: JobRole[] = [
  {
    id: 'job-fullstack-lead',
    title: 'Senior Full-Stack Cloud Engineer',
    department: 'Engineering & Innovation',
    requiredSkills: [
      { skillId: 'skill-react-18', minLevel: 'Expert', weight: 40 },
      { skillId: 'skill-typescript-5', minLevel: 'Advanced', weight: 30 },
      { skillId: 'skill-docker-k8s', minLevel: 'Advanced', weight: 30 },
    ],
  },
  {
    id: 'job-ai-engineer',
    title: 'Machine Learning Systems Architect',
    department: 'AI Research Lab',
    requiredSkills: [
      { skillId: 'skill-ml-python', minLevel: 'Advanced', weight: 60 },
      { skillId: 'skill-docker-k8s', minLevel: 'Intermediate', weight: 40 },
    ],
  },
];
